### ISSUE TITLE
A little > next to Shop Button

### ISSUE THREAD

**Issue by JoeFurfaro** [SophieCiardullo/svcrafted#1]
![image](https://user-images.githubusercontent.com/11153746/143933896-5370cbe4-8017-463f-9446-e05470fe7648.png)

Theres a little > next to the shop button on both pages. I think a tag is incorrectly closed somewhere (like maybe missing a / or there is an extra > somewhere!

**Comment by SophieCiardullo** [comment]
Removed an additional > from line 45.

**Comment by JoeFurfaro** [comment]
Well done!
