### ISSUE TITLE
Header Stays Transparent

### ISSUE THREAD

**Issue by JoeFurfaro** [SophieCiardullo/svcrafted#4]
Putting this here so you remember!

![image](https://user-images.githubusercontent.com/11153746/143934925-d7b9dec9-c063-49f5-ad62-5911a4be410b.png)

The header is currently staying transparent even after you scroll beyond HERO section.

Some options:

1. Make the header dark blue for now
2. Add JavaScript action listener for scrolling and check how far the user had scrolled, and update the background of header accordingly

**Comment by SophieCiardullo** [comment]
Have made header opaque with blue background. Will add dynamic transparency with JavaScript in the next unit.

**Comment by JoeFurfaro** [comment]
You can reopen issues later with the Reopen and comment button :)

(If you want to bring back this issue for the next Unit later)
