### ISSUE TITLE
Spaces Between Footer Links are Included in <a>

### ISSUE THREAD

**Issue by JoeFurfaro** [SophieCiardullo/svcrafted#5]
![image](https://user-images.githubusercontent.com/11153746/143935175-791b1350-3b73-47d4-9dc2-503e4e3bb194.png)

It's kinda hard to see, so I circled them in red. It looks like the spaces between your footer links are included in the anchor (`<a>`) tag, since you can see them showing up with blue underline! Just remove the spaces, and use `margin-right` and `margin-left` CSS properties to add more spacing, and you should be good to go 😄

**Comment by SophieCiardullo** [comment]
Removed spaces in anchor tags. Didn't add any additional spacing as it wasn't necessary.

**Comment by JoeFurfaro** [comment]
Can't wait to see the changes :)
